owner: dimaguy # Your GitHub organization or username, where this repository lives
repo: gh-status-page # The name of this repository
user-agent: dimaguy

sites:
  - name: linkpuff.me
    url: https://linkpuff.me/teapot/
    expectedStatusCodes:
      - 418
  - name: Luanet Webmin
    url: https://luanet.ddns.net:10000/
    __dangerous__disable_verify_peer: true
  - name: Home Assistant
    url: https://home.linkpuff.me/
  - name: Luanet Portainer
    url: https://linkpuff.me/portainer/
  - name: Luanet Gitea
    url: https://git.linkpuff.me/
  
  

status-website:
  cname: status.linkpuff.me
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  theme: ocean
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: WIP
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# See https://upptime.js.org/docs/configuration
